<?php

/*
 * Implementation of hook_menu
 */
function im_product_guide_menu(){
  $items = array();
  $items['admin/im/settings/product-guide-form'] = array(
    'title' => t('Product Guide form'),
    'page callback' => 'drupal_get_form',
    'file' => 'includes/im_product_guide.admin.inc',
    'page arguments' => array('im_product_guide_bo_form'),
    'access callback' => '_im_custom_settings_access',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

function _im_product_guide_landing_page(){
	if(variable_get('im_product_guide_url')!= ''){
    return '<iframe src= "'.variable_get('im_product_guide_url').'" width="'.variable_get('im_product_guide_iframe_width').'" height="'.variable_get('im_product_guide_iframe_height').'" frameborder="0"></iframe>';
	}
	elseif(variable_get('im_product_guide_ldap_fr_tag')!= ''){
	  return '<iframe src= "'.variable_get('im_product_guide_ldap_fr_tag').'" width="'.variable_get('im_product_guide_iframe_width').'" height="'.variable_get('im_product_guide_iframe_height').'" frameborder="0"></iframe>';
	}
	elseif(variable_get('im_product_guide_url')== '' && variable_get('im_product_guide_ldap_fr_tag')== ''){
	  return "";
	}
}

function im_product_guide_permission(){
	return array(
  'Product guide form' => array(
          'title' => t('Product guide form'),
          'description' => t('Allows user to select the url for product guide.'),
      ),
      );
}
